version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DJANGO_DEBUG: ${DJANGO_DEBUG}
    volumes:
      - ./tracker:/app
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672//
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    depends_on:
      - rabbitmq
    command: |
      bash -c "
        python manage.py collectstatic --noinput &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        django-admin compilemessages &&
        if [ \"${DJANGO_DEBUG}\" = \"true\" ]; then
          python manage.py runserver 0.0.0.0:8000;
        else
          gunicorn --bind 0.0.0.0:8000 tracker.wsgi:application;
        fi
      "
    ports:
      - "8000:8000"
    expose:
      - "8000"


  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DJANGO_DEBUG: ${DJANGO_DEBUG}
    command: celery -A tracker worker -l info
    volumes:
      - ./tracker:/app
    depends_on:
      - rabbitmq
      - django
    environment:
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672//

  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DJANGO_DEBUG: ${DJANGO_DEBUG}
    command: celery -A tracker beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -l info
    volumes:
      - ./tracker:/app
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672//

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./tracker:/app
    ports:
      - "80:80"
    depends_on:
      - django
