version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"



  django:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DJANGO_DEBUG: ${DJANGO_DEBUG}
    volumes:
      - ./tracker:/app
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672//
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - rabbitmq
      - postgres
    command: |
      bash -c "
        python manage.py collectstatic --noinput &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        if [ \"${DJANGO_DEBUG}\" = \"true\" ]; then
          python manage.py runserver 0.0.0.0:8000;
        else
          gunicorn --bind 0.0.0.0:8000 tracker.wsgi:application;
        fi
      "
    ports:
      - "8000:8000"
    expose:
      - "8000"


  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DJANGO_DEBUG: ${DJANGO_DEBUG}
    command: celery -A tracker worker -l info
    volumes:
      - ./tracker:/app
    depends_on:
      - rabbitmq
      - django
      - postgres
    environment:
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672//
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DJANGO_DEBUG: ${DJANGO_DEBUG}
    command: celery -A tracker beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -l info
    volumes:
      - ./tracker:/app
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672//
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./tracker:/app
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
